project:
  name: quickstart-cisco-asav-ravpn
  regions:
   - us-east-1
tests:
 default:
  template: ./templates/quickstart-cisco-asav-ravpn-master.yaml
  s3_bucket: ravpn-quickstart-test
  parameters:
   KeyPair: aws-cloudedge 
   AvailabilityZones: $[taskcat_getaz_2]
   VPCCIDR: 10.0.0.0/16
   PrivateSubnet1CIDR: 10.0.100.0/24 
   PrivateSubnet2CIDR: 10.0.200.0/24
   PublicSubnet1CIDR: 10.0.10.0/24
   PublicSubnet2CIDR: 10.0.20.0/24
   MgmtSubnet1CIDR: 10.0.1.0/24 
   MgmtSubnet2CIDR: 10.0.2.0/24
   NumberofAZs: 2
   QSS3BucketName: ravpn-quickstart-test
