project:
  name: quickstart-cisco-asav-ravpn
  regions:
   - us-east-1
  package_lambda: false
tests:
  2AZ-test:
    template: ./templates/quickstart-cisco-asav-ravpn-master.yaml
    # s3_bucket: maq-cisco-ravpn-quickstart
    parameters:
      NumberOfAZs: 2
      NumberOfASAv: 2
      KeyPair: sshvans
      AvailabilityZones: $[taskcat_getaz_2] #to be used with 1 or 2 ASAv
      #AvailabilityZones: $[taskcat_getaz_3] #to be used with 3 ASAv
      # AvailabilityZones: $[taskcat_getaz_4] #to be used with 4 ASAv
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      VPNUser: muffadal
      VPNPassword: "" # provide your own password
      OnPremFirewallPublicIP: 4.4.4.4
      OnPremCIDR: 192.168.128.0/24
      DnsName: example4.com
      SSHLockDownCIDR: 0.0.0.0/0
