project:
  name: quickstart-cisco-asav-ravpn
  regions:
   - us-east-1
tests:
 default:
  template: ./templates/quickstart-cisco-asav-ravpn-master.yaml
  # s3_bucket: maq-cisco-ravpn-quickstart
  parameters:
   NumberOfAZs: 4
   NumberOfASAv: 4
   KeyPair: sshvans
   # AvailabilityZones: $[taskcat_getaz_2] #to be used with 1 or 2 ASAv
   #AvailabilityZones: $[taskcat_getaz_3] #to be used with 3 ASAv
   AvailabilityZones: $[taskcat_getaz_4] #to be used with 4 ASAv
   QSS3BucketName: $[taskcat_autobucket]
   QSS3BucketRegion: us-west-2
   VPNUser: muffadal
   VPNPassword: cisco123
   OnPremFirewallPublicIP: 4.4.4.4
   OnPremCIDR: 192.168.128.0/24
   DnsName: example4.com
   SSHLockDownCIDR: 0.0.0.0/0
