AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cisco Systems - Creates the necessary policies, roles, security group and
  launches Cisco ASAv Instance(s)
Metadata:
  AWSAMIRegionMap:
    ap-northeast-1:
      HVM64: ami-0a3edbc2d49adc91d
    ap-northeast-2:
      HVM64: ami-0af3424b4002357f9
    ap-south-1:
      HVM64: ami-03cb656947137819f
    ap-southeast-1:
      HVM64: ami-0b7894d0f1e3bed77
    ap-southeast-2:
      HVM64: ami-007f91f7f2d993488
    ca-central-1:
      HVM64: ami-0dc3f05a9252ed7da
    eu-central-1:
      HVM64: ami-0ee46892e1b42f1ab
    eu-west-1:
      HVM64: ami-0e613bce9530d3420
    eu-west-2:
      HVM64: ami-0e86eefd5d88adc58
    eu-north-1:
      HVM64: ami-01eaad7c0b0952545
    sa-east-1:
      HVM64: ami-0901fb8b9d6e728e4
    us-east-1:
      HVM64: ami-0e7b5b45f2bb25f94
    us-east-2:
      HVM64: ami-089b209822f3c0760
    us-gov-west-1:
      HVM64: ami-c6a189a7
    us-west-1:
      HVM64: ami-0a6411e109ba2cd67
    us-west-2:
      HVM64: ami-0e8bfd9ebc1c0e78e
    ParameterGroups:
      - Label:
          default: ASAv Configuration
        Parameters:
          - InstanceTypeParam
          - KeyPair
          - MgmtSubnet1CIDR
          - MgmtSubnet2CIDR
          - VPCID
          - DnsName
    ParameterLabels:
      InstanceTypeParam:
        default: ASAv instance type
      KeyPair:
        default: keypair name
      MgmtSubnet1CIDR:
        default: Mgmt subnet 1
      MgmtSubnet2CIDR:
        default: Mgmt subnet 2
      VPCID:
        default: VPC ID
      DnsName:
        default: Dns name
Parameters:
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: ASAv instances will launch with this keypair
  InstanceTypeParam:
    Type: String
    Default: c5.large
    AllowedValues:
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
    Description: Select an instance size for the ASAv.
  MgmtSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.192.0/21
    Description: CIDR block for Mgmt subnet 1 in Availability Zone 1
    Type: String
  MgmtSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.200.0/21
    Description: CIDR block for Mgmt subnet 2 in Availability Zone 2
    Type: String
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Select VPC which ASAv will be deployed in
  DnsName:
    Type: String
    Description: DNS name of PrivateHostedZone
    Default: example.com
Mappings:
  AWSAMIRegionMap:
    ap-northeast-1:
      HVM64: ami-0a3edbc2d49adc91d
    ap-northeast-2:
      HVM64: ami-0af3424b4002357f9
    ap-south-1:
      HVM64: ami-03cb656947137819f
    ap-southeast-1:
      HVM64: ami-0b7894d0f1e3bed77
    ap-southeast-2:
      HVM64: ami-007f91f7f2d993488
    ca-central-1:
      HVM64: ami-0dc3f05a9252ed7da
    eu-central-1:
      HVM64: ami-0ee46892e1b42f1ab
    eu-west-1:
      HVM64: ami-0e613bce9530d3420
    eu-west-2:
      HVM64: ami-0e86eefd5d88adc58
    eu-north-1:
      HVM64: ami-01eaad7c0b0952545
    sa-east-1:
      HVM64: ami-0901fb8b9d6e728e4
    us-east-1:
      HVM64: ami-0e7b5b45f2bb25f94
    us-east-2:
      HVM64: ami-089b209822f3c0760
    us-gov-west-1:
      HVM64: ami-c6a189a7
    us-west-1:
      HVM64: ami-0a6411e109ba2cd67
    us-west-2:
      HVM64: ami-0e8bfd9ebc1c0e78e
Resources:
  PrivateHostedZone: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: 'Hosted zone'
      Name: !Ref DnsName
      VPCs: 
        - 
          VPCId: !Ref VPCID
          VPCRegion: !Ref "AWS::Region"
      HostedZoneTags: 
        - 
          Key: 'Name'
          Value: 'ASAvHostedZone'
  ASAvDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PrivateHostedZone
      Name: 
        !Join
          - '.'
          - - 'asav1'
            - !Ref DnsName
      TTL: '5'
      Type: A
      HealthCheckId: !Ref R53HealthCheck
      SetIdentifier: Frontend One
      Weight: 4
      ResourceRecords:
      - !GetAtt ASAvInstance.PublicIp
  R53HealthCheck: 
    Type: 'AWS::Route53::HealthCheck'
    Properties: 
      HealthCheckConfig: 
        IPAddress: !GetAtt ASAvInstance.PublicIp
        Port: 443
        Type: HTTP_STR_MATCH
        ResourcePath: '/'
        FullyQualifiedDomainName: !GetAtt ASAvInstance.PublicDnsName
        RequestInterval: 30
        FailureThreshold: 5
        MeasureLatency: true
        SearchString: '+CSCOE+'
      HealthCheckTags: 
        - 
          Key: Name
          Value: ASAv1Healthcheck
  MgmtSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCID
      CidrBlock: !Ref 'MgmtSubnet1CIDR'
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      Tags:
        - Key: Name
          Value: Mgmt subnet 1
  MgmtSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCID
      CidrBlock: !Ref 'MgmtSubnet2CIDR'
      AvailabilityZone: 
        Fn::Select: 
          - 1
          - Fn::GetAZs: ""
      Tags:
        - Key: Name
          Value: Mgmt subnet 2
  ASAvInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: Name
          Value: Cisco ASAv
      InstanceType: !Ref InstanceTypeParam
      KeyName: !Ref KeyPair
      ImageId: !FindInMap 
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - HVM64
Outputs:
  AccountId:
    Description: Amazon Account ID
    Value: !Ref 'AWS::AccountId'
  MgmtSubnet1CIDR:
    Description: Mgmt subnet 1 CIDR in Availability Zone 1
    Value: !Ref 'MgmtSubnet1CIDR'
    Export:
      Name: !Sub '${AWS::StackName}-MgmtSubnet1CIDR'
  MgmtSubnet1ID:
    Description: Mgmt subnet 1 ID in Availability Zone 1
    Value: !Ref 'MgmtSubnet1'
    Export:
      Name: !Sub '${AWS::StackName}-MgmtSubnet1ID'
  MgmtSubnet2CIDR:
    Description: Mgmt subnet 2 CIDR in Availability Zone 2
    Value: !Ref 'MgmtSubnet2CIDR'
    Export:
      Name: !Sub '${AWS::StackName}-MgmtSubnet2CIDR'
  MgmtSubnet2ID:
    Description: Mgmt subnet 2 ID in Availability Zone 2
    Value: !Ref 'MgmtSubnet2'
    Export:
      Name: !Sub '${AWS::StackName}-MgmtSubnet2ID'