AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cisco Systems - Creates the necessary policies, roles, security group and
  launches Cisco ASAv Instance(s)
Metadata:
  AWSAMIRegionMap:
    ap-northeast-1:
      HVM64: ami-0a3edbc2d49adc91d
    ap-northeast-2:
      HVM64: ami-0af3424b4002357f9
    ap-south-1:
      HVM64: ami-03cb656947137819f
    ap-southeast-1:
      HVM64: ami-0b7894d0f1e3bed77
    ap-southeast-2:
      HVM64: ami-007f91f7f2d993488
    ca-central-1:
      HVM64: ami-0dc3f05a9252ed7da
    eu-central-1:
      HVM64: ami-0ee46892e1b42f1ab
    eu-west-1:
      HVM64: ami-0e613bce9530d3420
    eu-west-2:
      HVM64: ami-0e86eefd5d88adc58
    eu-north-1:
      HVM64: ami-01eaad7c0b0952545
    sa-east-1:
      HVM64: ami-0901fb8b9d6e728e4
    us-east-1:
      HVM64: ami-0e7b5b45f2bb25f94
    us-east-2:
      HVM64: ami-089b209822f3c0760
    us-gov-west-1:
      HVM64: ami-c6a189a7
    us-west-1:
      HVM64: ami-0a6411e109ba2cd67
    us-west-2:
      HVM64: ami-0e8bfd9ebc1c0e78e
    ParameterGroups:
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - InstanceTypeParam
          - KeyPair
    ParameterLabels:
      InstanceTypeParam:
        default: ASAv instance type
      KeyPair:
        default: keypair name
Parameters:
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: ASAv instances will launch with this keypair
  InstanceTypeParam:
    Type: String
    Default: c5.large
    AllowedValues:
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
    Description: Select an instance size for the ASAv.
Mappings:
  AWSAMIRegionMap:
    ap-northeast-1:
      HVM64: ami-0a3edbc2d49adc91d
    ap-northeast-2:
      HVM64: ami-0af3424b4002357f9
    ap-south-1:
      HVM64: ami-03cb656947137819f
    ap-southeast-1:
      HVM64: ami-0b7894d0f1e3bed77
    ap-southeast-2:
      HVM64: ami-007f91f7f2d993488
    ca-central-1:
      HVM64: ami-0dc3f05a9252ed7da
    eu-central-1:
      HVM64: ami-0ee46892e1b42f1ab
    eu-west-1:
      HVM64: ami-0e613bce9530d3420
    eu-west-2:
      HVM64: ami-0e86eefd5d88adc58
    eu-north-1:
      HVM64: ami-01eaad7c0b0952545
    sa-east-1:
      HVM64: ami-0901fb8b9d6e728e4
    us-east-1:
      HVM64: ami-0e7b5b45f2bb25f94
    us-east-2:
      HVM64: ami-089b209822f3c0760
    us-gov-west-1:
      HVM64: ami-c6a189a7
    us-west-1:
      HVM64: ami-0a6411e109ba2cd67
    us-west-2:
      HVM64: ami-0e8bfd9ebc1c0e78e
Resources:
  ASAvInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: Name
          Value: Cisco ASAv
      InstanceType: !Ref InstanceTypeParam
      KeyName: !Ref KeyPair
      ImageId: !FindInMap 
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - HVM64
Outputs:
  AccountId:
    Description: Amazon Account ID
    Value: !Ref 'AWS::AccountId'
