AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cisco Systems - Master Stack - Creates VPC and the necessary policies, roles,
  security group and launches the Cisco ASAv RAVPN instances. **WARNING** You
  will be billed for the AWS resources used if you create a stack from this
  template.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Availability Zone Configuration
        Parameters:
          - AvailabilityZones
          - NumberOfAZs
      - Label:
          default: Network Configuration
        Parameters:
        #  - VPCCIDR
        #  - PrivateSubnet1ACIDR
        #  - PrivateSubnet1BCIDR
        #  - PublicSubnet1CIDR
        #  - PrivateSubnet2ACIDR
        #  - PrivateSubnet2BCIDR
        #  - PublicSubnet2CIDR
          - AvailabilityZones
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
      - Label:
          default: ASAv configuration
        Parameters:
          - KeyPair
    ParameterLabels:
      #VPCCIDR:
      #  default: VPC CIDR
      #PublicSubnet1CIDR:
      #  default: Public Subnet 1 CIDR
      #PublicSubnet2CIDR:
      #  default: Public Subnet 2 CIDR
      #PrivateSubnet1ACIDR:
      #  default: Private subnet 1A CIDR
      #PrivateSubnet1BCIDR:
      #  default: Private subnet 1B with dedicated network ACL CIDR
      #PrivateSubnet2ACIDR:
      #  default: Private subnet 2A CIDR
      #PrivateSubnet2BCIDR:
      #  default: Private subnet 2B with dedicated network ACL CIDR
      AvailabilityZones:
        default: Availability zones
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
      KeyPair:
        default: ASAv instance keypair
Parameters:
#  VPCCIDR:
#    AllowedPattern: >-
#      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
#    #Default: 10.0.0.0/16
#    Description: CIDR Block for the VPC
#    Type: String
#  PrivateSubnet1ACIDR:
#    AllowedPattern: >-
#      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
#    #Default: 10.0.0.0/19
#    Description: CIDR block for private subnet 1A located in Availability Zone 1
#    Type: String
#  PrivateSubnet1BCIDR:
#    AllowedPattern: >-
#      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
#    #Default: 10.0.192.0/21
#    Description: >-
#      CIDR block for private subnet 1B with dedicated network ACL located in
#      Availability Zone 1
#    Type: String
#  PrivateSubnet2ACIDR:
#    AllowedPattern: >-
#      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
#    #Default: 10.0.32.0/19
#    Description: CIDR block for private subnet 2A located in Availability Zone 2
#    Type: String
#  PrivateSubnet2BCIDR:
#    AllowedPattern: >-
#      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
#    #Default: 10.0.200.0/21
#    Description: >-
#      CIDR block for private subnet 2B with dedicated network ACL located in
#      Availability Zone 2
#    Type: String
#  PublicSubnet1CIDR:
#    AllowedPattern: >-
#      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
#    #Default: 10.0.10.0/24
#    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone 1
#    Type: String
#  PublicSubnet2CIDR:
#    AllowedPattern: >-
#      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
#    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
#    #Default: 10.0.20.0/24
#    Description: CIDR Block for the public DMZ subnet 2 located in Availability Zone 2
#    Type: String
  NumberOfAZs:
    AllowedValues:
      - '2'
      - '3'
      - '4'
    Default: '2'
    Description: >-
      Number of Availability Zones to use in the VPC. This must match your
      selections in the list of Availability Zones parameter.
    Type: String
  InstanceTypeParam:
    Type: String
    Default: c5.large
    AllowedValues:
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
    Description: Select an instance size for the ASAv.
  AvailabilityZones:
    Description: >-
      List of Availability Zones to use for the subnets in the VPC. Note: The
      logical order is preserved and only 2 AZs are used for this deployment.
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: us-west-2
    Description: >-
      The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted.
      When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-cisco-asav-ravpn/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: ASAv instance will launch with this keypair
Conditions:
  UsingDefaultBucket: !Equals 
    - !Ref QSS3BucketName
    - aws-quickstart
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 
        - >-
          https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml
        - S3Region: !If 
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref QSS3BucketRegion
          S3Bucket: !If 
            - UsingDefaultBucket
            - !Sub '${QSS3BucketName}-${AWS::Region}'
            - !Ref QSS3BucketName
      Parameters:
        AvailabilityZones: !Join 
          - ','
          - !Ref AvailabilityZones
        NumberOfAZs: !Ref NumberOfAZs
#        PrivateSubnet1ACIDR: !Ref PrivateSubnet1ACIDR
#        PrivateSubnet1BCIDR: !Ref PrivateSubnet1BCIDR
#        PrivateSubnet2ACIDR: !Ref PrivateSubnet2ACIDR
#        PrivateSubnet2BCIDR: !Ref PrivateSubnet2BCIDR
#        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
#        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
#        VPCCIDR: !Ref VPCCIDR
  ASAvStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 
        - >-
          https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/quickstart-cisco-asav-ravpn.yaml
        - S3Region: !If 
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref QSS3BucketRegion
          S3Bucket: !If 
            - UsingDefaultBucket
            - !Sub '${QSS3BucketName}-${AWS::Region}'
            - !Ref QSS3BucketName
      Parameters:
        InstanceTypeParam: !Ref InstanceTypeParam
        KeyPair: !Ref KeyPair
        VPCID: !GetAtt 'VPCStack.Outputs.VPCID'
#        PrivateSubnet1ACIDR: !Ref PrivateSubnet1ACIDR
#        PrivateSubnet1BCIDR: !Ref PrivateSubnet1BCIDR
#        PrivateSubnet2ACIDR: !Ref PrivateSubnet2ACIDR
#        PrivateSubnet2BCIDR: !Ref PrivateSubnet2BCIDR
#        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
#        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
#        VPCCIDR: !Ref VPCCIDR
  TGWStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 
        - >-
          https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/quickstart-cisco-asav-ravpn-tgw.yaml
        - S3Region: !If 
            - UsingDefaultBucket
            - !Ref 'AWS::Region'
            - !Ref QSS3BucketRegion
          S3Bucket: !If 
            - UsingDefaultBucket
            - !Sub '${QSS3BucketName}-${AWS::Region}'
            - !Ref QSS3BucketName
      Parameters:
        VPCID: !GetAtt 'VPCStack.Outputs.VPCID'
        PrivateSubnet1AID: !GetAtt 'VPCStack.Outputs.PrivateSubnet1AID'
Outputs:
  AccountId:
    Description: Amazon Account ID
    Value: !Ref 'AWS::AccountId'

